version: "3"
services:
  app:
    container_name: olx_checker
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    image: olx_checker
    stdin_open: true
    tty: true
    ports:
      - "8083:8083"
